### ISSUE TITLE
建议 Indent 不要翻译成 “意图”

### ISSUE THREAD

**Issue by chenhengjie123** [DroidTesting/android-espresso-doc-cn#1]
查看了很多 Android 相关文档，大多不会把 indent 翻译成 “意图”，一般都是直接不翻译，毕竟这个东西大部分接触过 Android 开发的都清楚是什么，说成 “意图” 反而反应不过来。

**Comment by lovexiaov** [comment]
已更新，请查看最新提交，谢谢建议
