### ISSUE TITLE
“AndroidJUnitRunner” 、“ATSL 中的 JUnit4 规则”章节内容与 Espresso Web 内容一致？

### ISSUE THREAD

**Issue by chenhengjie123** [DroidTesting/android-espresso-doc-cn#2]
[AndroidJUnitRunner 章节](https://github.com/DroidTesting/android-espresso-doc-cn/blob/master/chapter8.md) 、[ATSL 中的 JUnit4 规则](https://github.com/DroidTesting/android-espresso-doc-cn/blob/master/chapter9.md) 的内容与 [Espresso Web](https://github.com/DroidTesting/android-espresso-doc-cn/blob/master/chapter7.md) 的内容看起来是一致的，是官方文档如此还是编辑时出错了？

**Comment by lovexiaov** [comment]
是我的疏忽，已经更正，谢谢~
